/*
FAÇA UM PROGRAMA QUE CAUCULE E IMPRIMA O SALARIO A SER TRANSFERIDO PARA UM FUNCIONARIO
PARA REALIZAR O CAUCULO RECEBA O VALOR BRUTO DO SALARIO E O ADICIONAL DOS BENEFICIOS
O SALARIO A SER TRANSFERIDO É CALCULADO DA SEGUINTE MANEIRA
VALOR BRUTO - PERCENTUAL DE IMPOSTO MEDIANTE A FAIXA SALARIAL + ADICIONAL DE BENEFICIOS

ALICOTAS: 
DE R$ 0.00 A R$ 1100.00 = 5%
DE R$ 1100.00 A R$ 2500.00 = 10%
MAIOR QUE R$ 2500.00 = 15% 
*/

const {gets, print} = require('./funcoes-aux ex03');

const valorSalarioBruto = gets();
const valorAdicionalDosBeneficios = gets();

